name: Push Ordering Nuget Packages to GitHub Package Registry

on:
  push:
    branches:
      - master
    paths:
      - 'Fabillio.Ordering/**'
    tags:
  workflow_dispatch:

env:
  BUILD_CONFIGURATION: "Release"
  DOTNET_VERSION: "6.0.x"
  GITHUB_PACKAGE_REGISTRY_URL: https://proget-repository.extense.io/nuget/faktum-nuget/
  PROGET_FAKTUM_LOGIN: ${{ secrets.PROGET_FAKTUM_LOGIN }}
  PROGET_FAKTUM_PASSWORD: ${{ secrets.PROGET_FAKTUM_PASSWORD }}

jobs:
  nuget-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate build number
        id: build_number
        uses: paulhatch/semantic-version@v4.0.2
        with:
          tag_prefix: "v"
          bump_each_commit: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: ${{ env.GITHUB_PACKAGE_REGISTRY_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.PROGET_FAKTUM_NUGET_KEY }}

      - name: dotnet build and pack
        run: |
          cd Fabillio.Ordering
          dotnet restore
          dotnet build Fabillio.Ordering.Domain/Fabillio.Ordering.Domain.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=$1.0.0
          dotnet build Fabillio.Ordering.Public.Contracts/Fabillio.Ordering.Public.Contracts.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=$1.0.0
          dotnet build Fabillio.Ordering.Public.Events/Fabillio.Ordering.Public.Events.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=$1.0.0

          dotnet pack Fabillio.Ordering.Domain/Fabillio.Ordering.Domain.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=$1.0.0
          dotnet pack Fabillio.Ordering.Public.Contracts/Fabillio.Ordering.Public.Contracts.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=$1.0.0
          dotnet pack Fabillio.Ordering.Public.Events/Fabillio.Ordering.Public.Events.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=$1.0.0
          
      - name: nuget publish
        run: |
          cd Fabillio.Ordering
          dotnet nuget push *.Public.*/bin/Release/*.nupkg -k ${{ secrets.PROGET_FAKTUM_NUGET_KEY }} -s https://proget-repository.extense.io/nuget/faktum-nuget/ --skip-duplicate
          dotnet nuget push Fabillio.Ordering.Domain/bin/Release/*.nupkg -k ${{ secrets.PROGET_FAKTUM_NUGET_KEY }} -s https://proget-repository.extense.io/nuget/faktum-nuget/ --skip-duplicate